#!/usr/bin/env python2.7

import xmlrpclib
import json
import datetime as dt

api = xmlrpclib.ServerProxy("http://user:pass@localhost:8442/")

inboxMessages = json.loads(api.getAllInboxMessages())
print str(len(inboxMessages)) + " messages found!"

for msg in inboxMessages['inboxMessages']:
    if(msg['read'] == 0):
        print "Saving new message " + msg['msgid']
        f = open('/home/alex/.maildir/new/' + msg['msgid'], 'w')
        
        f.writelines([
            'Date: ' + dt.datetime.fromtimestamp(int(msg['receivedTime'])).strftime('%a, %d %b %Y %H:%M:%S %z') + "\n",
            'From: ' + msg['fromAddress'] + "\n",
            'To: ' + msg['toAddress'] + "\n",
            'Subject: ' + msg['subject'].decode('base64') + "\n",
            'Content-Type: text/plain; charset=utf-8' + "\n",
            'Content-Transfer-Encoding: base64' + "\n",
            'Message-ID: ' + msg['msgid'] + "\n",
            "\n" + msg['message'] + "\n"])

        f.close()

        print "Marking as read: " + msg['msgid']
        api.getInboxMessageByID(msg['msgid'], True)
